In [1]:
import numpy as np

In [2]:
# Declaring matrixes
A = np.array([[1, 3], [2, 1]])
B = np.array([[3, 0, 4], [-1, -2, 1]])
C = np.array([[-2, 1], [4, 1]])
D = np.array([[2], [6]])
print(D)
print("Array B has", B.shape[0], "rows.")
print("Array B has", B.shape[1], "columns.")

[[2]
 [6]]
Array B has 2 rows.
Array B has 3 columns.


In [3]:
# Matrix of any shape can be multiplied by a scalar
np.array([1, 2, 3]) * 2

array([2, 4, 6])

In [4]:
# Two matrices with the same shape can be added
np.array([1, 2]) + np.array([3, 4])

array([4, 6])

In [5]:
# Multiply each element in the matrix with another matrix
np.array([1, 2, 3]) * np.array([4, 5, 6])

array([ 4, 10, 18])

In [6]:
# Multiply every row by a constant
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) * np.array([1, 2, 3])

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [7]:
# Multiply every column by a constant
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) * np.array([1, 2, 3])[:, None]

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])

In [8]:
# Transpose matrix
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]).T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [9]:
# Quick vertical matrix
np.array([1, 2, 3])[:, None]

array([[1],
       [2],
       [3]])

In [10]:
# Regular matrix multiplication
np.array([[1, 2], [3, 4]]) @ np.array([[5, 6], [7, 8]])

array([[19, 22],
       [43, 50]])

In [11]:
# Dot product
np.array([1, 2, 3]).dot(np.array([4, 5, 6]))

32

In [12]:
# Cross product
np.cross([1, 2, 3], [4, 5, 6])

array([-3,  6, -3])

In [13]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
# Random matrix
np.random.randint(-10, 10, size=(3, 3))

array([[-10,  -5,  -6],
       [ -7,   1,  -3],
       [  7, -10,   1]])

In [15]:
# Matrix inverse
np.linalg.inv(np.array([[1, 2, 3], [4, 6, 6], [7, 8, 9]]))

array([[-0.5       , -0.5       ,  0.5       ],
       [-0.5       ,  1.        , -0.5       ],
       [ 0.83333333, -0.5       ,  0.16666667]])